version: "3.8"

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0.4
    ports:
      - "1883:1883"
    networks:
      - network_broker_adapter
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.8.3
    ports:
      - "8086"
    networks:
      - network_db_grafana
      - network_db_adapter
    environment:
      - INFLUXDB_DB=db
    volumes:
      - db_storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - "80:80"
    networks:
      - network_db_grafana
    environment:
      - GF_SERVER_HTTP_PORT=80
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2020
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  python_adapter:
    image: python_adapter:latest
    networks:
      - network_broker_adapter
      - network_db_adapter
    environment:
      - INFLUXDB_INTERNAL_PORT=8086
      - INFLUXDB_DB=db
      - INFLUXDB_HOST=influxdb
      - MQTT_BROKER_INTERNAL_PORT=1883
      - MQTT_BROKER_HOST=mqtt_broker
      - DEBUG_DATA_FLOW=true

volumes:
  db_storage:
  grafana_storage:

networks:
  network_broker_adapter:
  network_db_adapter:
  network_db_grafana:
